/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrgsIndexRouteImport } from './routes/orgs.index'
import { Route as OrgsOrgSlugRouteImport } from './routes/orgs.$orgSlug'
import { Route as OrgsOrgSlugProjectsIndexRouteImport } from './routes/orgs.$orgSlug.projects.index'
import { Route as OrgsOrgSlugProjectsProjectIdRouteImport } from './routes/orgs.$orgSlug.projects.$projectId'
import { Route as OrgsOrgSlugProjectsProjectIdIndexRouteImport } from './routes/orgs.$orgSlug.projects.$projectId.index'
import { Route as OrgsOrgSlugProjectsProjectIdLogsRouteImport } from './routes/orgs.$orgSlug.projects.$projectId.logs'
import { Route as OrgsOrgSlugProjectsProjectIdReportsRouteImport } from './routes/orgs.$orgSlug.projects.$projectId.reports'
import { Route as OrgsOrgSlugProjectsProjectIdTokensRouteImport } from './routes/orgs.$orgSlug.projects.$projectId.tokens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgSlugRoute = OrgsOrgSlugRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgSlugProjectsIndexRoute =
  OrgsOrgSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => OrgsOrgSlugRoute,
  } as any)
const OrgsOrgSlugProjectsProjectIdRoute =
  OrgsOrgSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => OrgsOrgSlugRoute,
  } as any)
const OrgsOrgSlugProjectsProjectIdIndexRoute =
  OrgsOrgSlugProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgSlugProjectsProjectIdRoute,
  } as any)
const OrgsOrgSlugProjectsProjectIdLogsRoute =
  OrgsOrgSlugProjectsProjectIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => OrgsOrgSlugProjectsProjectIdRoute,
  } as any)
const OrgsOrgSlugProjectsProjectIdReportsRoute =
  OrgsOrgSlugProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => OrgsOrgSlugProjectsProjectIdRoute,
  } as any)
const OrgsOrgSlugProjectsProjectIdTokensRoute =
  OrgsOrgSlugProjectsProjectIdTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => OrgsOrgSlugProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugRouteWithChildren
  '/orgs/': typeof OrgsIndexRoute
  '/orgs/$orgSlug/projects/$projectId': typeof OrgsOrgSlugProjectsProjectIdRouteWithChildren
  '/orgs/$orgSlug/projects/': typeof OrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$projectId/logs': typeof OrgsOrgSlugProjectsProjectIdLogsRoute
  '/orgs/$orgSlug/projects/$projectId/reports': typeof OrgsOrgSlugProjectsProjectIdReportsRoute
  '/orgs/$orgSlug/projects/$projectId/tokens': typeof OrgsOrgSlugProjectsProjectIdTokensRoute
  '/orgs/$orgSlug/projects/$projectId/': typeof OrgsOrgSlugProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugRouteWithChildren
  '/orgs': typeof OrgsIndexRoute
  '/orgs/$orgSlug/projects': typeof OrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$projectId/logs': typeof OrgsOrgSlugProjectsProjectIdLogsRoute
  '/orgs/$orgSlug/projects/$projectId/reports': typeof OrgsOrgSlugProjectsProjectIdReportsRoute
  '/orgs/$orgSlug/projects/$projectId/tokens': typeof OrgsOrgSlugProjectsProjectIdTokensRoute
  '/orgs/$orgSlug/projects/$projectId': typeof OrgsOrgSlugProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugRouteWithChildren
  '/orgs/': typeof OrgsIndexRoute
  '/orgs/$orgSlug/projects/$projectId': typeof OrgsOrgSlugProjectsProjectIdRouteWithChildren
  '/orgs/$orgSlug/projects/': typeof OrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$projectId/logs': typeof OrgsOrgSlugProjectsProjectIdLogsRoute
  '/orgs/$orgSlug/projects/$projectId/reports': typeof OrgsOrgSlugProjectsProjectIdReportsRoute
  '/orgs/$orgSlug/projects/$projectId/tokens': typeof OrgsOrgSlugProjectsProjectIdTokensRoute
  '/orgs/$orgSlug/projects/$projectId/': typeof OrgsOrgSlugProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/orgs/$orgSlug'
    | '/orgs/'
    | '/orgs/$orgSlug/projects/$projectId'
    | '/orgs/$orgSlug/projects/'
    | '/orgs/$orgSlug/projects/$projectId/logs'
    | '/orgs/$orgSlug/projects/$projectId/reports'
    | '/orgs/$orgSlug/projects/$projectId/tokens'
    | '/orgs/$orgSlug/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/orgs/$orgSlug'
    | '/orgs'
    | '/orgs/$orgSlug/projects'
    | '/orgs/$orgSlug/projects/$projectId/logs'
    | '/orgs/$orgSlug/projects/$projectId/reports'
    | '/orgs/$orgSlug/projects/$projectId/tokens'
    | '/orgs/$orgSlug/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/orgs/$orgSlug'
    | '/orgs/'
    | '/orgs/$orgSlug/projects/$projectId'
    | '/orgs/$orgSlug/projects/'
    | '/orgs/$orgSlug/projects/$projectId/logs'
    | '/orgs/$orgSlug/projects/$projectId/reports'
    | '/orgs/$orgSlug/projects/$projectId/tokens'
    | '/orgs/$orgSlug/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OrgsOrgSlugRoute: typeof OrgsOrgSlugRouteWithChildren
  OrgsIndexRoute: typeof OrgsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgSlug': {
      id: '/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgSlug/projects/': {
      id: '/orgs/$orgSlug/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgSlug/projects/'
      preLoaderRoute: typeof OrgsOrgSlugProjectsIndexRouteImport
      parentRoute: typeof OrgsOrgSlugRoute
    }
    '/orgs/$orgSlug/projects/$projectId': {
      id: '/orgs/$orgSlug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/orgs/$orgSlug/projects/$projectId'
      preLoaderRoute: typeof OrgsOrgSlugProjectsProjectIdRouteImport
      parentRoute: typeof OrgsOrgSlugRoute
    }
    '/orgs/$orgSlug/projects/$projectId/': {
      id: '/orgs/$orgSlug/projects/$projectId/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$projectId/'
      preLoaderRoute: typeof OrgsOrgSlugProjectsProjectIdIndexRouteImport
      parentRoute: typeof OrgsOrgSlugProjectsProjectIdRoute
    }
    '/orgs/$orgSlug/projects/$projectId/logs': {
      id: '/orgs/$orgSlug/projects/$projectId/logs'
      path: '/logs'
      fullPath: '/orgs/$orgSlug/projects/$projectId/logs'
      preLoaderRoute: typeof OrgsOrgSlugProjectsProjectIdLogsRouteImport
      parentRoute: typeof OrgsOrgSlugProjectsProjectIdRoute
    }
    '/orgs/$orgSlug/projects/$projectId/reports': {
      id: '/orgs/$orgSlug/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/orgs/$orgSlug/projects/$projectId/reports'
      preLoaderRoute: typeof OrgsOrgSlugProjectsProjectIdReportsRouteImport
      parentRoute: typeof OrgsOrgSlugProjectsProjectIdRoute
    }
    '/orgs/$orgSlug/projects/$projectId/tokens': {
      id: '/orgs/$orgSlug/projects/$projectId/tokens'
      path: '/tokens'
      fullPath: '/orgs/$orgSlug/projects/$projectId/tokens'
      preLoaderRoute: typeof OrgsOrgSlugProjectsProjectIdTokensRouteImport
      parentRoute: typeof OrgsOrgSlugProjectsProjectIdRoute
    }
  }
}

interface OrgsOrgSlugProjectsProjectIdRouteChildren {
  OrgsOrgSlugProjectsProjectIdLogsRoute: typeof OrgsOrgSlugProjectsProjectIdLogsRoute
  OrgsOrgSlugProjectsProjectIdReportsRoute: typeof OrgsOrgSlugProjectsProjectIdReportsRoute
  OrgsOrgSlugProjectsProjectIdTokensRoute: typeof OrgsOrgSlugProjectsProjectIdTokensRoute
  OrgsOrgSlugProjectsProjectIdIndexRoute: typeof OrgsOrgSlugProjectsProjectIdIndexRoute
}

const OrgsOrgSlugProjectsProjectIdRouteChildren: OrgsOrgSlugProjectsProjectIdRouteChildren =
  {
    OrgsOrgSlugProjectsProjectIdLogsRoute:
      OrgsOrgSlugProjectsProjectIdLogsRoute,
    OrgsOrgSlugProjectsProjectIdReportsRoute:
      OrgsOrgSlugProjectsProjectIdReportsRoute,
    OrgsOrgSlugProjectsProjectIdTokensRoute:
      OrgsOrgSlugProjectsProjectIdTokensRoute,
    OrgsOrgSlugProjectsProjectIdIndexRoute:
      OrgsOrgSlugProjectsProjectIdIndexRoute,
  }

const OrgsOrgSlugProjectsProjectIdRouteWithChildren =
  OrgsOrgSlugProjectsProjectIdRoute._addFileChildren(
    OrgsOrgSlugProjectsProjectIdRouteChildren,
  )

interface OrgsOrgSlugRouteChildren {
  OrgsOrgSlugProjectsProjectIdRoute: typeof OrgsOrgSlugProjectsProjectIdRouteWithChildren
  OrgsOrgSlugProjectsIndexRoute: typeof OrgsOrgSlugProjectsIndexRoute
}

const OrgsOrgSlugRouteChildren: OrgsOrgSlugRouteChildren = {
  OrgsOrgSlugProjectsProjectIdRoute:
    OrgsOrgSlugProjectsProjectIdRouteWithChildren,
  OrgsOrgSlugProjectsIndexRoute: OrgsOrgSlugProjectsIndexRoute,
}

const OrgsOrgSlugRouteWithChildren = OrgsOrgSlugRoute._addFileChildren(
  OrgsOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OrgsOrgSlugRoute: OrgsOrgSlugRouteWithChildren,
  OrgsIndexRoute: OrgsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
